spring.application.name=Instruction_Detection_Simulator
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.thymeleaf.cache=false
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/IDSimulator?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
spring.datasource.username =root
spring.datasource.password =